import * as WORKOUT_TYPE from './workout-types';

export default {
    [WORKOUT_TYPE.RUNNING]: 'Running',
    [WORKOUT_TYPE.CYCLING_TRANSPORT]: 'Cycling, transport',
    [WORKOUT_TYPE.CYCLING_SPORT]: 'Cycling, sport',
    [WORKOUT_TYPE.MOUNTAIN_BIKINGS]: 'Mountain biking',
    [WORKOUT_TYPE.SKATING]: 'Skating',
    [WORKOUT_TYPE.ROLLER_SKIING]: 'Roller skiing',
    [WORKOUT_TYPE.SKIING_CROSS_COUNTRY]: 'Skiing, cross country',
    [WORKOUT_TYPE.SKIING_DOWNHILL]: 'Skiing, downhill',
    [WORKOUT_TYPE.SNOWBOARDING]: 'Snowboarding',
    [WORKOUT_TYPE.KAYAKING]: 'Kayaking',
    [WORKOUT_TYPE.KITE_SURFING]: 'Kite surfing',
    [WORKOUT_TYPE.ROWING]: 'Rowing',
    [WORKOUT_TYPE.SAILING]: 'Sailing',
    [WORKOUT_TYPE.WINDSURFING]: 'Windsurfing',
    [WORKOUT_TYPE.FINTESS_WALKING]: 'Fitness walking',
    [WORKOUT_TYPE.GOLFING]: 'Golfing',
    [WORKOUT_TYPE.HIKING]: 'Hiking',
    [WORKOUT_TYPE.ORIENTEERING]: 'Orienteering',
    [WORKOUT_TYPE.WALKING]: 'Walking',
    [WORKOUT_TYPE.RIDING]: 'Riding',
    [WORKOUT_TYPE.SWIMMING]: 'Swimming',
    [WORKOUT_TYPE.CYCLING_INDOOR]: 'Cycling, Indoor',
    [WORKOUT_TYPE.OTHER]: 'Other',
    [WORKOUT_TYPE.AEROBICS]: 'Aerobics',
    [WORKOUT_TYPE.BADMINTON]: 'Badminton',
    [WORKOUT_TYPE.BASEBALL]: 'Baseball',
    [WORKOUT_TYPE.BASKETBALL]: 'Basketball',
    [WORKOUT_TYPE.BOXING]: 'Boxing',
    [WORKOUT_TYPE.CLIMBING_STAIRS]: 'Climbing stairs',
    [WORKOUT_TYPE.CRICKET]: 'Cricket',
    [WORKOUT_TYPE.ELLIPTICAL_TRAINING]: 'Elliptical training',
    [WORKOUT_TYPE.DANCING]: 'Dancing',
    [WORKOUT_TYPE.FENCING]: 'Fencing',
    [WORKOUT_TYPE.FOOTBALL_AMERICAN]: 'Football, American',
    [WORKOUT_TYPE.FOOTBALL_RUGBY]: 'Football, rugby',
    [WORKOUT_TYPE.FOOTBALL_SOCCER]: 'Football, soccer',
    [WORKOUT_TYPE.HANDBALL]: 'Handball',
    [WORKOUT_TYPE.HOCKEY]: 'Hockey',
    [WORKOUT_TYPE.PILATES]: 'Pilates',
    [WORKOUT_TYPE.POLO]: 'Polo',
    [WORKOUT_TYPE.SCUBA_DIVING]: 'Scuba diving',
    [WORKOUT_TYPE.SQUASH]: 'Squash',
    [WORKOUT_TYPE.TABLE_TENIS]: 'Table tennis',
    [WORKOUT_TYPE.TENNIS]: 'Tennis',
    [WORKOUT_TYPE.VOLEYBALL_BEACH]: 'Volleyball, beach',
    [WORKOUT_TYPE.VOLEYBALL_INDOOR]: 'Volleyball, indoor',
    [WORKOUT_TYPE.WEIGHT_TRAINING]: 'Weight training',
    [WORKOUT_TYPE.YOGA]: 'Yoga',
    [WORKOUT_TYPE.MARTINAL_ARTS]: 'Martial arts',
    [WORKOUT_TYPE.GYMNASTICS]: 'Gymnastics',
    [WORKOUT_TYPE.STEP_COUNTER]: 'Step counter',
    [WORKOUT_TYPE.CIRKUIT_TRAINING]: 'Circuit Training',
    [WORKOUT_TYPE.SKATEBOARDING]: 'Skateboarding',
    [WORKOUT_TYPE.CLIMBING]: 'Climbing',
    [WORKOUT_TYPE.KICK_SCOOTER]: 'Kick scooter',
    [WORKOUT_TYPE.CANICROSS]: 'Canicross',
    [WORKOUT_TYPE.FLOORBALL]: 'Floorball',
    [WORKOUT_TYPE.ICE_SKATING]: 'Ice skating',
    [WORKOUT_TYPE.RUNNING_TREADMILL]: 'Running (Treadmill)',
    [WORKOUT_TYPE.SURFING]: 'Surfing',
    [WORKOUT_TYPE.SNOWSHOEING]: 'Showshoeing',
    [WORKOUT_TYPE.WHEELCHAIR]: 'Wheelchair',
    [WORKOUT_TYPE.WALKING_TREADMILL]: 'Walking (Treadmill)',
    [WORKOUT_TYPE.STAND_UP_PADDLING]: 'Stand up paddling',
    [WORKOUT_TYPE.TRAIL_RUNNING]: 'Trail running',
    [WORKOUT_TYPE.ROWING_INDOORS]: 'Rowing (indoors)',
    [WORKOUT_TYPE.SKI_TOURING]: 'Ski touring',
    [WORKOUT_TYPE.ROPE_JUMPING]: 'Rope jumping',
    [WORKOUT_TYPE.STRETCHING]: 'Stretching',
    [WORKOUT_TYPE.PADDLE_TENNIS]: 'Paddle tennis',
    [WORKOUT_TYPE.PARAGLIDING]: 'Paragliding',
};
