import { WorkoutType } from './workout-type';

export default {
    [WorkoutType.RUNNING]: 'Running',
    [WorkoutType.CYCLING_TRANSPORT]: 'Cycling, transport',
    [WorkoutType.CYCLING_SPORT]: 'Cycling, sport',
    [WorkoutType.MOUNTAIN_BIKINGS]: 'Mountain biking',
    [WorkoutType.SKATING]: 'Skating',
    [WorkoutType.ROLLER_SKIING]: 'Roller skiing',
    [WorkoutType.SKIING_CROSS_COUNTRY]: 'Skiing, cross country',
    [WorkoutType.SKIING_DOWNHILL]: 'Skiing, downhill',
    [WorkoutType.SNOWBOARDING]: 'Snowboarding',
    [WorkoutType.KAYAKING]: 'Kayaking',
    [WorkoutType.KITE_SURFING]: 'Kite surfing',
    [WorkoutType.ROWING]: 'Rowing',
    [WorkoutType.SAILING]: 'Sailing',
    [WorkoutType.WINDSURFING]: 'Windsurfing',
    [WorkoutType.FINTESS_WALKING]: 'Fitness walking',
    [WorkoutType.GOLFING]: 'Golfing',
    [WorkoutType.HIKING]: 'Hiking',
    [WorkoutType.ORIENTEERING]: 'Orienteering',
    [WorkoutType.WALKING]: 'Walking',
    [WorkoutType.RIDING]: 'Riding',
    [WorkoutType.SWIMMING]: 'Swimming',
    [WorkoutType.CYCLING_INDOOR]: 'Cycling, Indoor',
    [WorkoutType.OTHER]: 'Other',
    [WorkoutType.AEROBICS]: 'Aerobics',
    [WorkoutType.BADMINTON]: 'Badminton',
    [WorkoutType.BASEBALL]: 'Baseball',
    [WorkoutType.BASKETBALL]: 'Basketball',
    [WorkoutType.BOXING]: 'Boxing',
    [WorkoutType.CLIMBING_STAIRS]: 'Climbing stairs',
    [WorkoutType.CRICKET]: 'Cricket',
    [WorkoutType.ELLIPTICAL_TRAINING]: 'Elliptical training',
    [WorkoutType.DANCING]: 'Dancing',
    [WorkoutType.FENCING]: 'Fencing',
    [WorkoutType.FOOTBALL_AMERICAN]: 'Football, American',
    [WorkoutType.FOOTBALL_RUGBY]: 'Football, rugby',
    [WorkoutType.FOOTBALL_SOCCER]: 'Football, soccer',
    [WorkoutType.HANDBALL]: 'Handball',
    [WorkoutType.HOCKEY]: 'Hockey',
    [WorkoutType.PILATES]: 'Pilates',
    [WorkoutType.POLO]: 'Polo',
    [WorkoutType.SCUBA_DIVING]: 'Scuba diving',
    [WorkoutType.SQUASH]: 'Squash',
    [WorkoutType.TABLE_TENIS]: 'Table tennis',
    [WorkoutType.TENNIS]: 'Tennis',
    [WorkoutType.VOLEYBALL_BEACH]: 'Volleyball, beach',
    [WorkoutType.VOLEYBALL_INDOOR]: 'Volleyball, indoor',
    [WorkoutType.WEIGHT_TRAINING]: 'Weight training',
    [WorkoutType.YOGA]: 'Yoga',
    [WorkoutType.MARTINAL_ARTS]: 'Martial arts',
    [WorkoutType.GYMNASTICS]: 'Gymnastics',
    [WorkoutType.STEP_COUNTER]: 'Step counter',
    [WorkoutType.CIRKUIT_TRAINING]: 'Circuit Training',
    [WorkoutType.SKATEBOARDING]: 'Skateboarding',
    [WorkoutType.CLIMBING]: 'Climbing',
    [WorkoutType.KICK_SCOOTER]: 'Kick scooter',
    [WorkoutType.CANICROSS]: 'Canicross',
    [WorkoutType.FLOORBALL]: 'Floorball',
    [WorkoutType.ICE_SKATING]: 'Ice skating',
    [WorkoutType.RUNNING_TREADMILL]: 'Running (Treadmill)',
    [WorkoutType.SURFING]: 'Surfing',
    [WorkoutType.SNOWSHOEING]: 'Showshoeing',
    [WorkoutType.WHEELCHAIR]: 'Wheelchair',
    [WorkoutType.WALKING_TREADMILL]: 'Walking (Treadmill)',
    [WorkoutType.STAND_UP_PADDLING]: 'Stand up paddling',
    [WorkoutType.TRAIL_RUNNING]: 'Trail running',
    [WorkoutType.ROWING_INDOORS]: 'Rowing (indoors)',
    [WorkoutType.SKI_TOURING]: 'Ski touring',
    [WorkoutType.ROPE_JUMPING]: 'Rope jumping',
    [WorkoutType.STRETCHING]: 'Stretching',
    [WorkoutType.PADDLE_TENNIS]: 'Paddle tennis',
    [WorkoutType.PARAGLIDING]: 'Paragliding',
};
